// Autogenerated file
#include "egg_stats.h"

using namespace egg_stats;

MultivariateNormal<3> egg_stats::expectations[EGG_TYPE_COUNT] = {
	// none
	(MultivariateNormal<3>) {
		(Matrix<float,3,1>() << 6.4, 23.75, 51.7).finished(),
		(Matrix<float,3,3>() << 2.98947368421, 2.26315789474, 2.33684210526,
		                        2.26315789474, 2.51315789474, 1.92105263158,
		                        2.33684210526, 1.92105263158, 2.95789473684).finished()
	},
	// white
	(MultivariateNormal<3>) {
		(Matrix<float,3,1>() << 19.5, 61.1, 89.45).finished(),
		(Matrix<float,3,3>() << 4.57894736842, 2.84210526316, 4.76315789474,
		                        2.84210526316, 3.25263157895, 4.00526315789,
		                        4.76315789474, 4.00526315789, 7.73421052632).finished()
	},
	// brown
	(MultivariateNormal<3>) {
		(Matrix<float,3,1>() << 14.65, 42.6, 79.8).finished(),
		(Matrix<float,3,3>() << 2.13421052632, 0.589473684211, 0.978947368421,
		                        0.589473684211, 2.14736842105, 1.75789473684,
		                        0.978947368421, 1.75789473684, 3.85263157895).finished()
	},
	// cream
	(MultivariateNormal<3>) {
		(Matrix<float,3,1>() << 10.3, 45.25, 71.75).finished(),
		(Matrix<float,3,3>() << 4.64210526316, 4.13157894737, 3.02631578947,
		                        4.13157894737, 7.03947368421, 5.38157894737,
		                        3.02631578947, 5.38157894737, 6.93421052632).finished()
	}
};

