// Autogenerated file
#include "egg_stats.h"

using namespace egg_stats;

EggExpectation egg_stats::expectations[EGG_TYPE_COUNT] = {
	// none
	(EggExpectation) {
		(NormValue) {-0.000921069309864, -0.00475641675811, 0.0726996956072},
		(NormValue) {5.58673480316e-05, 0.000113457289503, 0.000139744696723}
	},
	// white
	(EggExpectation) {
		(NormValue) {0.0175956813647, -0.000870353392202, 0.225919066849},
		(NormValue) {4.87794642089e-05, 3.87732950628e-05, 5.01031484869e-05}
	},
	// brown
	(EggExpectation) {
		(NormValue) {0.0179596594985, -0.00352546653715, 0.184203865086},
		(NormValue) {0.00015407602475, 0.000117635209205, 0.000111660644978}
	},
	// cream
	(EggExpectation) {
		(NormValue) {0.00555305331396, -0.00350896207469, 0.153204631949},
		(NormValue) {0.000106002930931, 6.83018911681e-05, 7.82349465662e-05}
	}
};

